name: year_prediction_msd 
dependencies:
  - jupyter=1.0.0
  - matplotlib=2.1.2
  - numpy=1.14.1
  - pandas=0.22.0
  - python=2.7.14
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - seaborn=0.8.1
  - pip:
    - tensorflow==1.5.0
